name: Checks

on:
  pull_request:
  push:
    branches:
      - 'main'

env:
  GO_VERSION: 1.18
  GOLANGCI_LINT_VERSION: v1.46.2

# This workflow runs for not-yet-reviewed external contributions and so it
# intentionally has no write access and only limited read access to the
# repository.
permissions:
  contents: read

jobs:
  lint:
    name: "lint"
    runs-on: ubuntu-22.04
    steps:
      - name: "Fetch source code"
        uses: actions/checkout@v2

      - name: Install Go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}

      - name: "go fmt check"
        run: |
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "The following file(s) do not conform to go fmt:"
            echo "$files"
            exit 1
          fi

      - name: "go vet"
        run: |
          go vet ./...

      - name: "go.mod and go.sum consistency check"
        run: |
          go mod tidy
          if [[ -n "$(git status --porcelain)" ]]; then
            echo >&2 "ERROR: go.mod/go.sum are not up-to-date. Run 'go mod tidy' and then commit the updated files."
            exit 1
          fi

      - name: "Download golang-lint"
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin ${{ env.GOLANGCI_LINT_VERSION }}
          golangci-lint version

      - name: "lint"
        run: |
          golangci-lint run -v

  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-22.04
    steps:
      - name: "Fetch source code"
        uses: actions/checkout@v2

      - name: Install Go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}

      - name: "Unit tests"
        run: |
          go test ./...

  configuration_tests:
    name: "Config File Tests"
    runs-on: ubuntu-22.04
      - name: "Fetch source code"
        uses: actions/checkout@v2

      - name: Install Go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}

      - name: compile binary
        run: |
          make
          devconsul help
